project:
  type: website

toc: true
resources:
  - docs/decisions/attachments
website:
  repo-url: https://github.com/V-Sekai/v-sekai-proposals
  repo-branch: master
  repo-actions: edit
  title: "V-Sekai Decisions"
  reader-mode: true
  opengraph: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "V-Sekai"
        contents:
          - README.md
          - CHANGELOG.md
      - section: "Decisions"
        contents:
          - decisions.qmd
  page-footer: 
    left: "2022, V-Sekai" 
    right: 
      - icon: github
        href: https://github.com/V-Sekai

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true



