project:
  type: website

toc: true
resources:
  - docs/decisions/attachments
website:
  repo-url: https://github.com/V-Sekai/v-sekai-proposals
  repo-branch: master
  repo-actions: edit
  title: "V-Sekai Proposals"
  page-navigation: true
  opengraph: true
  navbar:
    search: true
    left:
      - text: "Overview"
        file: index.md
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/VSekaiOfficial
    style: "docked"
    search: true
    contents:
      - CHANGELOG.md
      - decisions.qmd
      - roadmap_q2_2022.qmd
  page-footer: 
    left: "2022, V-Sekai" 
    right: 
      - icon: github
        href: https://github.com/V-Sekai

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true



