project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io
  repo-branch: master
  repo-actions: edit
  title: "V-Sekai Proposals"
  page-navigation: true
  opengraph: true
  toc: true
  navbar:
    left:
      - text: "Overview"
        file: CHANGELOG.md
    tools:
      - icon: twitter
        href: https://twitter.com/VSekaiOfficial
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - features.md
      - documentation_guide.md
      - CHANGELOG.md
      - decisions.qmd
  page-footer: 
    left: "2022, V-Sekai" 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai
  search:
    algolia:
      index-name: prod_vsekai
      application-id: 2IE1M5GC5G
      search-only-api-key: 4f2b015cb39d6d0ed415e222489bfaa9

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css

filters:
  - quarto

freeze: true

editor: visual
