project:
  type: book
  output-dir: _site

resources:
  - docs/decisions/attachments

book:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io
  repo-branch: master
  repo-actions: edit
  title: "V-Sekai Documentation"
  page-navigation: true
  opengraph: true
  toc: true
  toc-depth: 0
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/VSekaiOfficial
  author: "V-Sekai Community"
  date: "2021/05/01"
  chapters:
    - index.qmd
    - features.md
    - part: "Changelog"
      chapters: 
        - changelog/README.md
        - changelog/changelog-2021-04.md
        - changelog/changelog-2021-05.md
        - changelog/changelog-2021-06.md
        - changelog/changelog-2021-07.md
        - changelog/changelog-2021-08.md
        - changelog/changelog-2021-09.md
        - changelog/changelog-2021-10.md
        - changelog/changelog-2021-11.md
        - changelog/changelog-2022-01.md
        - changelog/changelog-2022-02.md
        - changelog/changelog-2022-03.md
        - changelog/changelog-2022-04.md
        - changelog/changelog-2022-05.md
        - changelog/changelog-2022-06.md
    - part: "Decisions 2020"
      chapters: 
      - decisions/2020/20200602-manage-backend-with-k3s.md
      - decisions/2020/20200721-discord-bot.md
      - decisions/2020/20200721-discord-inworld-portal.md
      - decisions/2020/20200729-entity-networking.md
    - part: "Decisions 2021"
      chapters: 
      - decisions/2021/20210212-add-build-notifications.md
      - decisions/2021/20210212-use-log4brains-to-manage-the-adrs.md
      - decisions/2021/20210212-use-markdown-architectural-decision-records.md
      - decisions/2021/20210523-basis-universal-import.md
      - decisions/2021/20210523-complete-gltf2-vrm-import-and-export-pipeline-in-godot-engine.md
      - decisions/2021/20210523-distribute-trusted-clients-with-notary.md
      - decisions/2021/20210523-retarget-motion-for-vrm-type-models.md
      - decisions/2021/20210523-simplfy-meshes-and-lods-better-with-quads.md
      - decisions/2021/20210525-shadermotion-to-bvh.md
      - decisions/2021/20210528-trial-install-of-gravity-for-kubernetes.md
      - decisions/2021/20210529-performance-profiling.md
      - decisions/2021/20210601-store-presentation-and-book-content-via-lottie-2.md
      - decisions/2021/20210612-flow-avatar-asset-pipeline.md
      - decisions/2021/20210622-shadermotion-to-godot-engine.md
      - decisions/2021/20210707-transfer-animations-by-baking-reset.md
      - decisions/2021/20210710-verify-pr-workflow.md
      - decisions/2021/20210715-Material-Addon-Blender.md
      - decisions/2021/20210715-portable-world-content.md
      - decisions/2021/20210724-Spreadsheet-animation-preview.md
      - decisions/2021/20210811-disconnected-ipfs.md
      - decisions/2021/20210811-game-workflow-membrane.md
      - decisions/2021/20210811-glb-in-video.md
      - decisions/2021/20210811-godot-transparency.md
      - decisions/2021/20210811-minecraft-voxel.md
      - decisions/2021/20210811-min-spec-v-sekai.md
      - decisions/2021/20210811-neural-blend-shape-rigging.md
      - decisions/2021/20210811-omi-glb.md
      - decisions/2021/20210811-soiree-party.md
      - decisions/2021/20210811-spoke-to-v-sekai.md
      - decisions/2021/20211005-bridge-music-to-xr.md
      - decisions/2021/20211005-create-add-spring-bones-to-vrm-models.md
      - decisions/2021/20211005-create-sop-for-vrm-creation.md
      - decisions/2021/20211005-improve-meshing-results-by-subdivision-in-godot-engine.md
      - decisions/2021/20211005-solve-mocap-by-connecting-mediapipe-to-blender.md
      - decisions/2021/20211005-test-google-mediapipe.md
      - decisions/2021/20211005-use-kvm-to-test-our-amd-apu-test-computer-via-barrier.md
      - decisions/2021/20211005-use-materialx-for-asset-interchange.md
      - decisions/2021/20211005-want-to-summon-friends-and-acquaintances-via-presence.md
      - decisions/2021/20211005-want-to-use-the-same-cluster-for-the-same-web-and-native.md
      - decisions/2021/20211005-we-want-to-proxy-udp-datagrams-at-production-quality-of-service.md
      - decisions/2021/20211031-1000-player-servers.md
      - decisions/2021/20211031-arc-radial-menu.md
      - decisions/2021/20211031-bake-a-materialx-into-a-custom-godot-standardmaterial3d.md
      - decisions/2021/20211031-bake-blend-shape-to-skeleton-animation.md
      - decisions/2021/20211031-benchmark-animation-playback.md
      - decisions/2021/20211031-character-workshop.md
      - decisions/2021/20211031-cicd-export-v-sekai.md
      - decisions/2021/20211031-client-and-mast.md
      - decisions/2021/20211031-construct-the-virtual-world.md
      - decisions/2021/20211031-create-a-demo-viewer-gallery.md
      - decisions/2021/20211031-export-import-testing-via-robot-framework-and-swiftshader.md
      - decisions/2021/20211031-extract-proposals-into-proposals.md
      - decisions/2021/20211031-face-motion-tracking-requires-standard-shapes.md
      - decisions/2021/20211031-gltf-importer-should-bind-animation-players-to-the-closest-root-node.md
      - decisions/2021/20211031-godot-database-viewer-for-proposals.md
      - decisions/2021/20211031-have-better-user-developer-experience.md
      - decisions/2021/20211031-have-wires-in-3d.md
      - decisions/2021/20211031-how-to-make-a-v-sekaigodot-update.md
      - decisions/2021/20211031-keep-a-changelog.md
      - decisions/2021/20211031-make-a-place-to-record.md
      - decisions/2021/20211031-meeting-area.md
      - decisions/2021/20211031-membrane-framework-streaming-mixer.md
      - decisions/2021/20211031-openvr-for-godot-engine.md
      - decisions/2021/20211031-phase-out-groups-terminology-for-vskdefault.md
      - decisions/2021/20211031-plausable-npc-behaviour.md
      - decisions/2021/20211031-play-preprocessed-animations-on-any-vrm-model.md
      - decisions/2021/20211031-run-the-maintance-scripts-from-windows-in-unix-mode-with-msys2.md
      - decisions/2021/20211031-script-as-a-binary.md
      - decisions/2021/20211031-standard-backup-procedures.md
      - decisions/2021/20211031-streaming-godot-to-opensoundcontrol.md
      - decisions/2021/20211031-stream-shader-motion.md
      - decisions/2021/20211031-thorvg.md
      - decisions/2021/20211031-tire-model-car-sim.md
      - decisions/2021/20211031-update-uro-for-godot-4.md
      - decisions/2021/20211031-use-bpr-to-rank-skeleton-bone-names.md
      - decisions/2021/20211031-use-our-custom-fullbody-ik.md
      - decisions/2021/20211031-verification-tools.md
      - decisions/2021/20211031-vmd-on-vrm-animationtree-node.md
      - decisions/2021/20211031-voip.md
      - decisions/2021/20211103-bolster-creating-the-metaverse.md
      - decisions/2021/20211103-use-platform-called-vfx-reference-platform.md
      - decisions/2021/20211104-research-mesh-tooling-with-kaolin.md
      - decisions/2021/20211104-research-mesh-tooling-with-nglod.md
      - decisions/2021/20211105-have-an-webxr-version-of-v-sekai.md
      - decisions/2021/20211105-iterate-faster-on-wasgo-prototype-by-using-godot-34.md
      - decisions/2021/20211105-take-a-list-of-3d-points-to-triangulate-in-godot-engine.md
      - decisions/2021/20211105-use-single-player-webxr-in-godot-engine-to-prototype-cassie.md
      - decisions/2021/20211106-preview-materialx-materials-on-the-web-in-godot-engine-2.md
      - decisions/2021/20211108-integrate-with-blender.md
      - decisions/2021/20211108-invisible-meshes-appear-via-the-use-of-the-exporter.md
      - decisions/2021/20211109-create-a-vrm-character-by-experimenting-with-written-workflows.md
      - decisions/2021/20211112-degrade-v-sekais-networking-model-to-work-in-2d-and-with-webrtc.md
      - decisions/2021/20211113-file-or-attestation-for-virtual-worlds-using-ssh-signatures.md
      - decisions/2021/20211113-learn-how-to-scale-v-sekai-using-bots-and-multipliers.md
      - decisions/2021/20211117-allow-godot-asset-library-browser-to-use-alternative-sources.md
      - decisions/2021/20211128-stabilize-godot-engine-updates-by-delaying-to-2-week-cycles.md
      - decisions/2021/20211129-create-a-godot-engine-asset-store-service-on-elixir-and-on-sqlite.md
      - decisions/2021/20211130-avoid-avatar-breaking-by-following-quality-checklist.md
      - decisions/2021/20211130-fix-critical-bugs-by-creating-an-upstream-pull-request.md
      - decisions/2021/20211207-for-godot-engine-changes-use-a-decision-flowchart.md
      - decisions/2021/20211211-create-steamdeck-hardware-proxy-by-fedora-kinoite.md
      - decisions/2021/20211212-create-steamdeck-hardware-proxy-by-fedora-silverblue.md
      - decisions/2021/20211214-create-an-open-metaverse-by-working-on-v-sekai.md
      - decisions/2021/20211220-network-the-ubisoft-mixer-server.md
      - decisions/2021/20211229-run-meetings-using-lean-coffee.md
      - decisions/2021/20211229-stream-a-character-from-a-webcam-to-the-vmc-protocol.md
    - part: "Decisions 2022"
      chapters: 
      - decisions/2022/20220108-bake-blend-shapes-to-skeletons-for-performance.md
      - decisions/2022/20220113-change-transform-by-crdt.md
      - decisions/2022/20220118-convert-gltf-to-a-scene.md
      - decisions/2022/20220118-to-make-it-easier-to-upload-maps-and-avatars-templates.md
      - decisions/2022/20220130-optimize-cicd.md
      - decisions/2022/20220130-to-record-decisions-write-a-proposal.md
      - decisions/2022/20220131-elixir-desktop-uro.md
      - decisions/2022/20220131-github-actions-support.md
      - decisions/2022/20220131-run-own-infrastructure.md
      - decisions/2022/20220202-gltf-extensions-for-interoperability.md
      - decisions/2022/20220203-create-default-animation-set.md
      - decisions/2022/20220205-cicd-to-pass by-fixing-spatial-audio-branch.md
      - decisions/2022/20220206-logging-notifications-from-discord.md
      - decisions/2022/20220207-virtual-pets.md
      - decisions/2022/20220215-uro-deployment-process.md
      - decisions/2022/20220217-omi-chan-oni-chan.md
      - decisions/2022/20220222-know-where-we-re-going-by-planning-vsekai.md
      - decisions/2022/20220222-rank-bone-names-with-transformer.md
      - decisions/2022/20220222-rank-bone-skeletons-with-xgboost.md
      - decisions/2022/20220222-rank-skeleton-bone-names-with-catboost.md
      - decisions/2022/20220223-store-source-VSK_map-files-via-DVC.md
      - decisions/2022/20220224-v-sekai-version-two-plan.md
      - decisions/2022/20220228-v-sekai-version-three-plan.md
      - decisions/2022/20220317-baserow.io-truenas.md
      - decisions/2022/20220317-protect-minumum-spec-steam-deck.md
      - decisions/2022/20220317-use-spec-rough-metal.md
      - decisions/2022/20220318-merge-retargeting-pr.md
      - decisions/2022/20220515-profile-using-perf.md
      - decisions/2022/20220531-elixir-uro-dev.md
      - decisions/2022/20220531-truenas-scale.md
      - decisions/2022/20220601-lightweight-quality-avatars.md
      - decisions/2022/20220605-gocd-pipeline-reset.md
      - decisions/2022/20220605-host-internal-baserow.md
      - decisions/2022/20220624-webcam-to-posed-characters.md
  appendices:
    - documentation_guide.md
  page-footer: 
    left: "2022, V-Sekai" 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai
  search:
    location: navbar
    type: overlay
    algolia:
      index-name: prod_vsekai
      application-id: 2IE1M5GC5G
      search-only-api-key: d02c6d33503386189654aefbc3c00153

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css

filters:
  - quarto

freeze: true

editor: visual
