name: Feature implementation proposal
description: Propose a possible solution to solve an engine limitation
body:

- type: markdown
  attributes:
    value: |
      - Short title of solved problem and solution.

- type: Status
  attributes:
    label: Describe the status of the issue.
    multiple: true
    options:
      - proposed
      - draft
      - rejected
      - accepted
      - deprecated
      - superseded by
  validations:
    required: true

- type: Deciders
  attributes:
    label: List the deciders of the issue.
    placeholder: V-Sekai,
  validations:
    required: true

- type: Tags
  attributes:
    label: Describe the tags of the issue.
    description: This is important to know the *context* in which the feature is being proposed. Features used in real-world projects are more likely to be added.
    placeholder: V-Sekai,
  validations:
    required: true

- type: Context and Problem Statement
  attributes:
    label: Describe the problem or limitation you are having in your project
    description: Describe the context and problem statement, e.g., in free form using two to three sentences. You may want to articulate the problem in the form of a question.
    placeholder: Example - "A 3D space game with heavy use of cut-out animation"
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the proposed option and how it helps to overcome the problem or limitation
    placeholder: Example - "The 3D selection tools are cumbersome to use."
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the feature / enhancement and how it helps to overcome the problem or limitation
    placeholder: Example - "Add keyboard shortcuts to select groups of nodes quickly."
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams
    placeholder: Example - "When the user presses Ctrl + Shift + G, select all nodes that have the group..."
  validations:
    required: true

- type: textarea
  attributes:
    label: Positive Consequences
    placeholder: e.g., improvement of quality attribute satisfaction, follow-up decisions required, …
  validations:
    required: false

- type: textarea
  attributes:
    label: Negative Consequences
    placeholder: e.g., compromising quality attribute, follow-up decisions required, …
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      Option graveyard:
      
      - Option: <!-- [List the proposed options no longer open for consideration.] -->
      - Rejection Reason: <!-- [List the reasons for the rejection: (the Bad traits)] -->
  validations:
    required: false

- type: textarea
  attributes:
    label: If this enhancement will not be used often, can it be worked around with a few lines of script?
    placeholder: Example - "Implementing mesh merging systems is not a few lines of script."
  validations:
    required: true

- type: textarea
  attributes:
    label: Is there a reason why this should be core and done by us?
    placeholder: Example - "This is about improving the 3D editor usability out of the box."
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      References:
      
      - [Link type](link to decision)
  validations:
    required: false
