name: Request a proposal
description: Request a proposal to be written.
labels: [proposal-request]
body:

- type: markdown
  attributes:
    value: |
      - Write a descriptive proposal request above.

- type: textarea
  attributes:
    label: Request description
    description: |
      Describe your request briefly. What doesn't work, and how do you expect it to work instead?
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true
