name: Publish Quarto
on:
  push:
    branches:
      - master
jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install nomnoml
          mkdir -p _site
          npx nomnoml ./vsekai_roadmap_2022.nomnoml ./vsekai_roadmap_2022.svg
          npx nomnoml ./plan.nomnoml ./plan.svg
          npx nomnoml ./plan-ecosystem.nomnoml ./plan-ecosystem.svg
          npx nomnoml ./plan-cassie.nomnoml ./plan-cassie.svg
      - uses: quarto-dev/quarto-actions/install-quarto@v1
      - run: |
          quarto render .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          TARGET_FOLDER: .
