name: Publish Quarto
on:
  push:
    branches:
      - master
jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: quarto-dev/quarto-actions/install-quarto@v1
      - run: |
          quarto render .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          TARGET_FOLDER: log4brains
